version: "3.7"
services:
  shadowsocks:
    image: qmcgaw/ss-server
    container_name: shadowsocks
    network_mode: bridge
    ports:
      - 8388:8388/tcp
      - 8388:8388/udp
    environment:
      - PASSWORD=password
      - TZ=
    restart: always
