version: "3.7"

services:
  vscode:
    image: qmcgaw/godevcontainer
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - 6060:6060/tcp
      - 8388:8388/tcp
      - 8388:8388/udp
    entrypoint: zsh -c "while sleep 1000; do :; done"
