name: Docker build
on:
  pull_request:
    branches: [master]
    paths-ignore:
      - .devcontainer
      - .github/workflows/build-release.yml
      - .github/workflows/buildx-latest.yml
      - .github/workflows/dockerhub-description.yml
      - .github/workflows/labels.yml
      - .github/CODEOWNERS
      - .github/CONTRIBUTING.md
      - .github/FUNDING.yml
      - .github/labels.yml
      - examples
      - LICENSE
      - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build .
